config/routes.rb
Rails.application.routes.draw do
  resources :fees_structures

  resources :faculties
  get 'departments/faculty'
  resources :notices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'home#index'
get 'home/developers'

get 'departments/index'
get 'departments/cse'
get 'departments/mechanical'
get 'departments/sci_humanity'
get 'home/visionAndMission'
get 'home/aboutUs'
get 'home/principalMassege'
get 'home/administration'
get 'home/committee'
get 'home/photoGallery'
get 'admission/BTech'
get 'admission/procedure'
get 'admission/fees_structure'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/models/fees_structure.rb
class FeesStructure < ApplicationRecord
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/admission_controller.rb
class AdmissionController < ApplicationController

	def BTech

	end

	def procedure
		
	end

	def fees_structure
    	@fees = FeesStructure.all
  	end
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	
	
	def index
		
	end

	def cse
		
	end


	def mechanical
		
	end

	def sci_humanity
		
	end

	def faculty
    	@faculty = Faculty.all
    end
    
    

end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  

  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :department, :qualification, :designation, :Experience, :specialization, :contact, :email)
    end
end

app/controllers/fees_structures_controller.rb
class FeesStructuresController < ApplicationController
  before_action :set_fees_structure, only: [:show, :edit, :update, :destroy]

  # GET /fees_structures
  # GET /fees_structures.json
  def index
    @fees_structures = FeesStructure.all
  end

  
  # GET /fees_structures/1
  # GET /fees_structures/1.json
  def show
  end

  # GET /fees_structures/new
  def new
    @fees_structure = FeesStructure.new
  end

  # GET /fees_structures/1/edit
  def edit
  end

  # POST /fees_structures
  # POST /fees_structures.json
  def create
    @fees_structure = FeesStructure.new(fees_structure_params)

    respond_to do |format|
      if @fees_structure.save
        format.html { redirect_to @fees_structure, notice: 'Fees structure was successfully created.' }
        format.json { render :show, status: :created, location: @fees_structure }
      else
        format.html { render :new }
        format.json { render json: @fees_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees_structures/1
  # PATCH/PUT /fees_structures/1.json
  def update
    respond_to do |format|
      if @fees_structure.update(fees_structure_params)
        format.html { redirect_to @fees_structure, notice: 'Fees structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @fees_structure }
      else
        format.html { render :edit }
        format.json { render json: @fees_structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees_structures/1
  # DELETE /fees_structures/1.json
  def destroy
    @fees_structure.destroy
    respond_to do |format|
      format.html { redirect_to fees_structures_url, notice: 'Fees structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fees_structure
      @fees_structure = FeesStructure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fees_structure_params
      params.require(:fees_structure).permit(:program, :session, :year, :feesinfo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@notice = Notice.all
	end
	def aboutUs
		
	end
	def visionAndMission
		
	end
	def campusLife
		
	end
	def principalMassege
		
	end
	def photoGallery
		
	end
	def administration
		
	end
	def committee
		
	end
	def developers
		
	end
	def photoGallery
		
	end

end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:notice_name, :notice_detail, :notice_type)
    end
end

app/helpers/admission_helper.rb
module AdmissionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/fees_structures_helper.rb
module FeesStructuresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/admission/BTech.html.erb
<section>
<div class="col-md-10 offset-md-1">
	<article class="item-page">


		<h1><span style="font-size: 14pt;"><strong><span style="color: #0000ff;">Under Graduate Programmes and Fee Structure</span></strong></span></h1>
		<p>&nbsp;</p>
		<p><span style="font-size: 12pt;">Institute offer following under graduate programmes -</span></p>
		
		<table class= "table"style="height: 200px;"  border="1">
			<tbody>
				<tr>
					<td width="auto	">
						<p style="text-align: center;"><span style="font-size: 10pt;"><strong>Course</strong></span></p>
					</td>
					<td style="text-align: center;" width="auto">
						<p><span style="font-size: 10pt;"><strong>Branch</strong></span></p>
					</td>
					<td style="text-align: center;" width="auto">
						<p><span style="font-size: 10pt;"><strong>No. of Seats</strong></span></p>
					</td>
					<td style="text-align: center;" width="auto">
						<p><span style="font-size: 10pt;"><strong>Tution Fee Waiver Scheme Seats </strong></span></p>
					</td>
					
				</tr>
				
				
				<tr style="text-align: center;">
					<td width="auto">
						<p><span style="font-size: 10pt;">B. Tech.</span></p>
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">Computer Science Engineering</span></p>
						
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">60</span></p>
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">3</span></p>
					</td>
				</tr>
				
				<tr style="text-align: center;">
					<td width="auto">
						<p><span style="font-size: 10pt;">B. Tech.</span></p>
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">Mechanical Engineering</span></p>
						
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">60</span></p>
					</td>
					<td width="auto">
						<p><span style="font-size: 10pt;">3</span></p>
					</td>
				</tr>
				
			</tbody>
		</table>
		<p><span style="font-size: 10pt;">&nbsp;</span></p>
		<p><span style="font-size: 10pt;">&nbsp;<strong> B.Tech. (Bachelor of Technology) Admissions</strong></span></p>
		<p style="text-align: justify;"><span style="font-size: 10pt;">From the year 2013, the State Government of Madhya Pradesh has decided to admit students to Engineering Colleges of Madhya Pradesh through Joint Entrance Exam (JEE Mains) conducted at All India level by CBSE. The admission procedure is conducted in three phases : Round 1, Round 2 and College Level Counselling.</span></p>
		<p style="text-align: justify;"><span style="font-size: 10pt;">The date of availability , last date of submission of form and other details are announced by the DTE in leading Newspapers of the State. For more information student may consult&nbsp;<span style="color: #0000ff; font-size: 12pt;"><a style="color: #0000ff;" href="https://dte.mponline.gov.in" rel="alternate">https://dte.mponline.gov.in</a></span></span></p>
		
				
		<p style="text-align: justify; padding-left: 30px;"><span style="font-size: 10pt;"><span style="text-decoration: underline;">BASIC ELIGIBILITY CRITERIA</span>: The candidates shall be considered for admission to First Year B.E. course who have passed the qualifying examination (i.e. Class 12th of 10+2 System) or equivalent examination with Physics, Chemistry &amp; Mathematics subjects.</span></p>
		<p style="text-align: justify; padding-left: 30px;"><span style="font-size: 10pt;">&nbsp;</span></p>
		
		<p><span style="color: #ff0000; font-size: 12pt;"><strong><span style="text-decoration: underline;">FEES STRUCTURE FOR 2019-20 ADMITTED</span></strong></span></p>
		
		<!-- <p><span style="font-size: 12pt;"><strong><span style="color: #ff0000;"><span style="color: #0000ff;">Note:</span>&nbsp;</span></strong> <strong><span style="color: #008000;">For 2019-20 admissions, UG Tuition Fees will be increased by Government of Madhya Pradesh and when finalized will be applicable </span></strong></span><strong><span style="color: #008000; font-size: 12pt;">to all the students taking admission.</span></strong>&nbsp;</p> -->
		<!-- <p>&nbsp;</p> -->
		<p><span style="font-size: 14pt;"><strong> FEE STRUCTURE (CS/ME)</strong></span></p>
		
		<p><a href="https://drive.google.com/open?id=1jDrD5VyyVS75mB4CXvUmxJ4VxrcC0qJf" target="blank"> <b>B.Tech. 1st Year Fee structure</b></a></p>
			
		</article>

</div>
</section>

app/views/admission/fees_structure.html.erb
<section>
	<div>
		<div class="container">
			<h2>Fees Structure</h2>
			           
			<table class="table">
				<thead>
					<tr>
						<th>Course</th>
						<th>Session</th>
						<th>year</th>
						<th>download</th>
					</tr>
				</thead>
				<tbody>
					<% @fees.each do |fees| %>
						<tr>
							<td><%= fees.program %></td>
							<td><%= fees.session %></td>
							<td><%= fees.year %></td>
							<td><a href=<%= fees.feesinfo %> target="blank"> download</a></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</section>
<a ></a>

app/views/admission/procedure.html.erb
<section>
	<div class="col-md-10 offset-md-1">
		<h3><strong>Dr. APJ Abdul Kalam University Institute of Technology, Jhabua (UIT Jhabua) Admission 2019: </strong></h3>
		<p>Dr. APJ Abdul Kalam University Institute of Technology, Jhabua (UIT Jhabua) was established in 2015 by the Government of Madhya Pradesh. The college is affiliated to RGPV.</p>
		<ul>
			<li>A candidate seeking admission to B.Tech, must have passed the 10+2 examination from a recognized board with Physics &amp; Mathematics as main subjects along with either Chemistry, Biotechnology or Biology as the third subject with at least 45% marks in aggregate.</li>
			<li>Students have to qualify JEE Main in order to secure admission in B.Tech program.</li>
			<li>The counselling for admission is conducted by the Directorate of Technical Education, Government of MP through online off campus procedure.</li>

			<li>For more information student may consult&nbsp;<span style="color: #0000ff; font-size: 12pt;"><a style="color: #0000ff;" href="https://dte.mponline.gov.in" rel="alternate">https://dte.mponline.gov.in</a></span></span></li>
		</ul>

	</div>
	<style type="text/css">
		p,li{
			text-align: justify;
		}
	</style>
</section>

app/views/departments/cse.html.erb
<div>
	<div class="row">
		<div class="col-md-9">
			<div class="container-fluid ">
				<div class="vis-mis-container">
					<div class="vis-mis-head bg-primary">
						<p>Computer Science & Engineering Department</p>
					</div>	
					<h5><b>Vision</b></h5>
					<p style="text-align: justify">To shape the young Technocrats with highest quality of value based Technical & Ethical foundation to contribute towards building a strong mankind.</p>
				</div>
			</div>
		</div>
		<div class="col-md-3">
			<%= render 'layouts/sideMenu' %>
		</div>
	</div>
</div>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<section>
  <div class="container"> 
    <p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table class="table table-sm ">
  <thead class="thead-dark"> 
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Qualification</th>
      <th>designation</th>
       <th>Experience</th>
      <th>Specialization</th>
      <th>Contact</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.department %></td>
        <td><%= faculty.qualification %></td>
        <td><%= faculty.designation %></td>
        <td><%= faculty.Experience %></td>
        <td><%= faculty.specialization %></td>
        <td><%= faculty.contact %></td>
        <td><%= faculty.email %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

  </div>
</section>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<section>
  <div class="container-fluid">
    <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @faculty.department %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @faculty.qualification %>
</p>
<p>
  <strong>designation:</strong>
  <%= @faculty.designation %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @faculty.Experience %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @faculty.specialization %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @faculty.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @faculty.email %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>

  </div>
</section>

app/views/fees_structures/edit.html.erb
<h1>Editing Fees Structure</h1>

<%= render 'form', fees_structure: @fees_structure %>

<%= link_to 'Show', @fees_structure %> |
<%= link_to 'Back', fees_structures_path %>

app/views/fees_structures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees Structures</h1>

<table>
  <thead>
    <tr>
      <th>Program</th>
      <th>Session</th>
      <th>Year</th>
      <th>Feesinfo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees_structures.each do |fees_structure| %>
      <tr>
        <td><%= fees_structure.program %></td>
        <td><%= fees_structure.session %></td>
        <td><%= fees_structure.year %></td>
        <td><%= fees_structure.feesinfo %></td>
        <td><%= link_to 'Show', fees_structure %></td>
        <td><%= link_to 'Edit', edit_fees_structure_path(fees_structure) %></td>
        <td><%= link_to 'Destroy', fees_structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fees Structure', new_fees_structure_path %>

app/views/fees_structures/new.html.erb
<h1>New Fees Structure</h1>

<%= render 'form', fees_structure: @fees_structure %>

<%= link_to 'Back', fees_structures_path %>

app/views/fees_structures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program:</strong>
  <%= @fees_structure.program %>
</p>

<p>
  <strong>Session:</strong>
  <%= @fees_structure.session %>
</p>

<p>
  <strong>Year:</strong>
  <%= @fees_structure.year %>
</p>

<p>
  <strong>Feesinfo:</strong>
  <%= @fees_structure.feesinfo %>
</p>

<%= link_to 'Edit', edit_fees_structure_path(@fees_structure) %> |
<%= link_to 'Back', fees_structures_path %>

app/views/home/contactUs.html.erb
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				
			</div>
			<div class="col-md-6">
				
			</div>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<div id="footer" class="bg-voilet-blue">
	<div class="container-fluid">
		<footer>
			<div class="row">
				<div class="col-md-3 col-sm-6 footer-col">
					<div class="text-center">
						<%= link_to image_tag( 'rgpvlogo.png', width: "80" , height: "80", :class => "img-fluid"), root_path%>
					</div>
					<div class="text-center">
						<h5>Dr. APJ Abdul Kalam UIT, Jhabua</h5>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 footer-col">
				<div class= "footer-col-inner">
						<h5>Call Us</h5>
					</div>
					<div class="footer-col-inner-content">
						<p>For technical Support</br>
						09407554170</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 footer-col">
					<div class= "footer-col-inner">
						<h5>Anti Ragging</h5>
					</div>
					<div class="footer-col-inner-content">
						<p>For More Information on Anti Ragging <a href="#">Click here</a></p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 footer-col">
					<div class= "footer-col-inner">
						<h5>Contact Us</h5>
					</div>
					<div class="footer-col-inner-content">
						<p>Dr. APJ Abdul Kalam UIT</br>
						Govt. Polytechnic campus</br>
						Kishanpuri, Jhabua, 457661</br>
						Tel: 07392-244216</br>
						Email: uitrgpvjhabua@gmail.com</p>
					</div>
				</div>
			</div>
		</footer>
	</div>
	<div class="bg-dark">
		<div class=" container footer-bottom">
			<div class="row">
				<div class="col-md-6 text-center">
				<div class="copyright">
						<p>© All Rights Reserved for UIT Jhabua.</p>
					</div>
				</div>
				<div class="col-md-6 text-center">
					<div class="dev">
						<!-- <p>Meet the <%#= link_to "developers.", home_developers_path%></p> -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<div class="bg-voilet-blue top-nav">
  <div class="container">
    <nav class="navbar navbar-expand-md bg-voilet-blue navbar-dark ">

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">Menu 
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav text-center mx-md-auto " >
          <li class="nav-item navbar-menu ">
            <%= link_to "HOME", root_path, class: 'nav-link'%>
          </li>
          <li class="nav-item dropdown navbar-menu">
            <a class="nav-link" tabindex="0">ABOUT </a>
            <ul class=" bg-voilet-blue  dropdown-menu">
              <li><%= link_to "About Institute", home_aboutUs_path, class: 'nav-link'%></li>
              <li><%= link_to "Vision and Mission", home_visionAndMission_path, class: 'nav-link'%></li>
              <li><%= link_to "Principal massege", home_principalMassege_path, class: 'nav-link'%></li>
              <li><%= link_to "Administration", home_administration_path, class: 'nav-link'%></li>
              <li><%= link_to "Committees", home_committee_path, class: 'nav-link'%></li>
              
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link">ACADEMICS</a>
            <ul class=" bg-voilet-blue dropdown-menu">
              <li><%= link_to "Departments", departments_index_path, class: 'nav-link'%></li>
               <li><%= link_to "Faculties", departments_faculty_path, class: 'nav-link'%></li>
              <li><a class="nav-link" tabindex="-1" href="#">Academic Calender</a></li>
              <li><a class="nav-link" tabindex="-1" href="#">Examination</a></li>
              <li><a class="nav-link" tabindex="-1" href="#">Time Table</a></li>
              <li><%= link_to "Fee Structure", admission_fees_structure_path, class: 'nav-link'%></li>
              
            </ul>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link">ADMISSION</a>
            <ul class=" bg-voilet-blue dropdown-menu">
              <li><%= link_to "Admission procedure", admission_procedure_path, class: 'nav-link'%></li>
              <!-- <li><a class="nav-link" tabindex="-1" href="#">Admission Criteria</a></li> -->
              <li><%= link_to "Programme", admission_BTech_path, class: 'nav-link'%></li>
            </ul>
          </li> 
          
          <li class="nav-item dropdown">
            <a class="nav-link" >STUDENT ZONE</a>
            <ul class=" bg-voilet-blue dropdown-menu">
              <li><a class="nav-link" tabindex="-1" href="#">Student Activities</a></li>
              <li><a class="nav-link" tabindex="-1" href="#">Scholarship</a></li>
              <li><a class="nav-link" tabindex="-1" href="#">NSS</a></li>
              <li><a class="nav-link" tabindex="-1" href="#">UIT SC/ST Cell</a></li>
            </ul>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">EVENTS</a>
          </li> 

        </ul>
      </div> 
    </nav>
  </div>
</div>

app/views/layouts/_sideMenu.html.erb
<section style="margin: 15px 5px;">
<div>
	<div class="sidenav">
		<div class="sidenav-link">
			<%= link_to "About Institute", home_aboutUs_path, class: 'btn btn-primary'%>
		</div>
		<div class="sidenav-link">
			<%= link_to "Vision and Mission", home_visionAndMission_path, class: 'btn btn-primary'%>
		</div>
		<div class="sidenav-link">
			<%= link_to "Principal Message", home_principalMassege_path, class: 'btn btn-primary'%>
		</div>
		<div class="sidenav-link">
			<%= link_to "Administration", home_administration_path, class: 'btn btn-primary'%>
		</div>
		<div class="sidenav-link">
			<%= link_to "Committee", home_committee_path, class: 'btn btn-primary'%>
		</div>
	</div>
</div>
</section>
<style type="text/css">
	


</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uitjhabua</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>Notice name</th>
      <th>Notice detail</th>
      <th>Notice type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.notice_name %></td>
        <td><%= notice.notice_detail %></td>
        <td><%= notice.notice_type %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notice name:</strong>
  <%= @notice.notice_name %>
</p>

<p>
  <strong>Notice detail:</strong>
  <%= @notice.notice_detail %>
</p>

<p>
  <strong>Notice type:</strong>
  <%= @notice.notice_type %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>